api_platform:
  path_segment_name_generator: api_platform.path_segment_name_generator.dash
  mapping:
    paths: [
      '%kernel.project_dir%/src/Entity',
    ]
  patch_formats:
    json: [ 'application/merge-patch+json' ]
    jsonapi: [ 'application/vnd.api+json' ]
  formats:
    json: [ 'application/json' ]
    jsonapi: [ 'application/vnd.api+json' ]
    jsonld: [ 'application/ld+json' ]
    html: [ 'text/html' ]
    graphql: [ 'application/graphql' ]
  swagger:
    versions: [ 3 ]
    api_keys:
      apiKey:
        name: Authorization
        type: header
  
  defaults:
    stateless: true
    # Good cache defaults
    cache_headers:
      vary: [ 'Content-Type', 'Authorization', 'Origin' ]
    pagination_maximum_items_per_page: 50
    pagination_client_items_per_page: true
  
  eager_loading:
    enabled: false